version: "2.4"

################################################################################

services:
  tetris:
    runtime: nvidia
    environment:
      # Configure Nvidia Docker interface.
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_REQUIRE_CUDA=cuda>=10.1
    